micronaut:
  application:
    name: issue
netty:
  default:
    allocator:
      max-order: 3
---
flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
---
r2dbc:
  datasources:
    default:
      url: "r2dbc:h2:mem:///default?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
      username: sa
      password: ""
---

jpa:
  default:
    entity-scan:
      packages: 'io.micronaut.data.issue.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true